### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Xenate** [sandogeorge/webtalk#19]
I have gotten the server running on Ubuntu 20.04 but whenever I go to http://localhost:5000/install I get an internal error with error code 500. it states "Existence error: procedure st_render:st_render_file/4 does not exist in term" in the terminal running the server. Can anybody help me. On the webpage it says "SWI-Prolog httpd at thelambda-Surface-Pro-6". Can anyone give me some insight on how to fix this?

**Comment by rdroe** [comment]
I get the same. It's almost like a key library is missing, or something.

**Comment by rdroe** [comment]
@Xenate Try running this is in swi prolog beforehand. 

```
? pack_install(simple_template).
```

There are prompts to answer, but it may install the simple_template stuff you need.

**Comment by sandogeorge** [comment]
I think this was indeed an issue of installing simple_template. Closing.
