### ISSUE TITLE
Startup errors when using SWI-Prolog 8.1.11

### ISSUE THREAD

**Issue by pmoura** [sandogeorge/webtalk#7]
Using the startup command from the `README.md` file:

```bash
$ swilgt -s app.lgt
```

results in several compilation errors when using SWI-Prolog 8.1.11 (and likely any 8.x version). These errors are caused by the use of strings instead of atoms in calls to the SWI-Prolog predicates `http_handler /3` and `http_location_by_id /2`. Changing the strings to atoms fixes all the errors and allow loading of the `app.lgt` file to succeed.

**Comment by sandogeorge** [comment]
Thanks for reporting this @pmoura. I will take a look at it soon.

**Comment by rdroe** [comment]
after a successful install (and PR #20), i still have an error that i think relates to what @pmoura mentioned. 

![Screen Shot 2020-12-26 at 1 09 14 PM](https://user-images.githubusercontent.com/5402341/103157719-b1889580-477b-11eb-8746-9ec21ef0193a.png)

it's as if `true` is being passed as a location id somewhere. i'm looking into it.

**Comment by sandogeorge** [comment]
Fixed by 2e020dfc63ff3d0ea85bc9d11c0c6235e48a21cc and 0d982fbd6dbc45d769a7964f5366964a45d9e95c.
